// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA41DDQSPpqajOy6ysc_CbWe3OcHwRSEfM',
    appId: '1:339482593695:web:bae285656339a91444d5aa',
    messagingSenderId: '339482593695',
    projectId: 'chatti-e09fb',
    authDomain: 'chatti-e09fb.firebaseapp.com',
    storageBucket: 'chatti-e09fb.appspot.com',
    measurementId: 'G-HVL9G7YSWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8_nCgV6ejuTNmEefJxdhJUwOkneKr6Vs',
    appId: '1:339482593695:android:d9278033c2e8ed7044d5aa',
    messagingSenderId: '339482593695',
    projectId: 'chatti-e09fb',
    storageBucket: 'chatti-e09fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXGgwErSPWN9DuAYRZQIwx980IDfsuaeU',
    appId: '1:339482593695:ios:3cb2e8e6e8209cda44d5aa',
    messagingSenderId: '339482593695',
    projectId: 'chatti-e09fb',
    storageBucket: 'chatti-e09fb.appspot.com',
    iosClientId: '339482593695-oks6ai78n58er6i4qdidb2k72s7go2th.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXGgwErSPWN9DuAYRZQIwx980IDfsuaeU',
    appId: '1:339482593695:ios:3cb2e8e6e8209cda44d5aa',
    messagingSenderId: '339482593695',
    projectId: 'chatti-e09fb',
    storageBucket: 'chatti-e09fb.appspot.com',
    iosClientId: '339482593695-oks6ai78n58er6i4qdidb2k72s7go2th.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChat',
  );
}
